### ISSUE TITLE
Supporting more <language>envs?

### ISSUE THREAD

**Issue by createdbypete** [fisherman/rbenv#3]
The `rbenv` Ruby version manager has been replicated many times for different languages. I'm currently making use of the following but I'm sure there are more:

- rbenv (ruby)
- nodenv (node)
- exenv (elixir)

Due these all being pretty much exact replicas besides the name change I have duplicated the files in this repo on my machine and simply replaced `rbenv` for `<language>env` where appropriate and it all seems to Just Work™.

So I wonder if this plugin should be expanded to just support all the `<language>env` in some way or if they should still be separate repos? My concern with separate repos is replicating changes across them all but perhaps given the rate of change is very small that is not such an issue.

Any thoughts?

**Comment by daenney** [comment]
The problem is there's no way of knowing when those things diverge. Right now the configuration of those plugins is roughly the same and the same behaviour is expected. But when that changes, which could happen, this breaks down.

Considering we haven't had to touch rbenv or pyenv in about a year I'd say the rate of code changes isn't really an issue.

**Comment by createdbypete** [comment]
Ideal for fisherman plugin "search-ability" for them to be separate too. So I offer up these repos for fisherman ownership if you want them. Just a find and replace of the rbenv plugin you wrote so everything is still attributed to you (besides the commit).

https://github.com/createdbypete/fisherman-exenv
https://github.com/createdbypete/fisherman-nodeenv

**Comment by daenney** [comment]
I'm not actively working on rbenv or pyenv right now (or a user of nodenv or exenv) but perhaps @jbucaran wants to pull them in?

**Comment by jbucaran** [comment]
Thanks @createdbypete! I've just sent you an invite to the org. You may transfer them to fisherman as well as create any new repos for other plugins you'd like to work on. 👋 

For them to show up in the [online search](https://fisherman.github.io), they'll need to be added to the [_index_](https://github.com/fisherman/index).

**Comment by createdbypete** [comment]
@jbucaran transferred the repos. I forgot to setup description and tags before transferring though but not a huge deal. Will update the index shortly.

**Comment by jbucaran** [comment]
@createdbypete Sounds great Pete. Welcome aboard!
