### ISSUE TITLE
Command not found on startup

### ISSUE THREAD

**Issue by dpipkin** [fisherman/rbenv#5]
System: Ubuntu 16.04 (Windows Subsystem for Linux)
fish version: 2.7.1
rbenv version: rbenv 1.1.1-37-g1c772d5

When I start Ubuntu (the app from the Windows Store) it says
```
rbenv: command not found. See https://github.com/rbenv/rbenv
```
before fish starts with the welcome message.

Is there a way to prevent that from showing up?

**Comment by ragesoss** [comment]
@dpipkin I had this on my Debian system as well. It appears to be related to the note in the README: the rbenv plugin loads (and initializes rbenv) before `config.fish` is runs, and at the time it runs, the rbenv executable is not in your PATH.

I was able to fix it by creating `.config/fish/conf.d/000-env.fish` with the same export I had previously used in my `.bashrc`:

```
export PATH="$HOME/.rbenv/bin:$PATH"
```

That or something similar may work for you.

**Comment by dpipkin** [comment]
Awesome! That worked for me, I just made it fishy.

Contents of `.config/fish/conf.d/000-env.fish`:
```fish
# Add rbenv to path
set -x PATH $PATH $HOME/.rbenv/bin
```
